# auto generated by update_py.py

from . import comm_pb2 as comm_pb
from . import frame_pb2 as frame_pb


def _msgHeartBeatStr(self):
    return '<hb fist_type={} fist_name={} desc_name={} status={} mounted={}>'.format(
        comm_pb.FistType.Name(self.fist_type), self.fist_name, self.desc_name,
        comm_pb.HeartbeatStatus.Name(self.hb_status), self.router_name
    )


comm_pb.MsgHeartBeat.__str__ = _msgHeartBeatStr
