# auto generated by update_py.py
class DMError(Exception):
    def __init__(self, code, message):
        super(DMError, self).__init__("{} (code:{})".format(message, code))
        self.code = code
        self.msg = message
